package rewrite

import (
	"encoding/json"
	"fmt"
	"html/template"
	"mime"
	"path"
	"strings"

	"go-press/core/content"
)

// SEOMeta is the page-level SEO contract passed from core/theme to templates.
//
// Core builders populate safe defaults for home, archive, and single pages.
// Plugins can filter SEOMeta before rendering to provide per-content overrides,
// robots directives, social images, or structured-data extensions.
type SEOMeta struct {
	Title         string `json:"title"`
	Description   string `json:"description"`
	CanonicalURL  string `json:"canonical_url"`
	OGTitle       string `json:"og_title"`
	OGDescription string `json:"og_description"`
	OGImage       string `json:"og_image"`
	OGType        string `json:"og_type"`   // "website", "article"
	Robots        string `json:"robots"`    // "index,follow"
	JSONLD        string `json:"json_ld"`   // JSON-LD structured data
	SiteIcon      string `json:"site_icon"` // Favicon URL (rendered as <link rel="icon">)
}

// SEOBuilder constructs default SEO metadata from site settings and content.
//
// It is deliberately deterministic and side-effect free. Admin-managed site
// icon/title overrides and plugin-provided per-content overrides are layered on
// by theme helpers after the builder returns.
type SEOBuilder struct {
	siteURL  string
	siteName string
	rewrite  *Engine
}

// NewSEOBuilder creates a new SEO builder.
func NewSEOBuilder(siteURL, siteName string, rewrite *Engine) *SEOBuilder {
	return &SEOBuilder{
		siteURL:  strings.TrimSuffix(siteURL, "/"),
		siteName: siteName,
		rewrite:  rewrite,
	}
}

// SiteName returns the static site name used when this builder was created.
func (b *SEOBuilder) SiteName() string {
	if b == nil {
		return ""
	}
	return b.siteName
}

// ForContent generates metadata for a single content page.
//
// The canonical URL is derived from the rewrite engine so SEO output stays in
// sync with the active theme's registered content models.
func (b *SEOBuilder) ForContent(c *content.Content, typeDef *content.ContentTypeDef) SEOMeta {
	url := b.siteURL + b.rewrite.BuildURL(typeDef.Name, c.Slug)

	meta := SEOMeta{
		Title:        c.Title + " | " + b.siteName,
		CanonicalURL: url,
		OGTitle:      c.Title,
		OGType:       "article",
		Robots:       "index,follow",
	}

	if c.Excerpt != "" {
		meta.Description = truncate(c.Excerpt, 160)
		meta.OGDescription = meta.Description
	}

	if c.ImageURL != "" {
		meta.OGImage = b.absoluteURL(c.ImageURL)
	}

	// Generate JSON-LD
	meta.JSONLD = b.buildArticleJSONLD(c, url)

	return meta
}

// ForArchive generates SEO metadata for an archive page.
func (b *SEOBuilder) ForArchive(typeDef *content.ContentTypeDef) SEOMeta {
	return b.ForArchiveTitle(typeDef, typeDef.LabelPlural)
}

// ForArchiveTitle generates SEO metadata for an archive page with a localized
// presentation title supplied by the theme runtime.
func (b *SEOBuilder) ForArchiveTitle(typeDef *content.ContentTypeDef, archiveTitle string) SEOMeta {
	if archiveTitle == "" {
		archiveTitle = typeDef.LabelPlural
	}
	url := b.siteURL + b.rewrite.BuildArchiveURL(typeDef.Name)
	return SEOMeta{
		Title:        archiveTitle + " | " + b.siteName,
		Description:  archiveTitle,
		CanonicalURL: url,
		OGTitle:      archiveTitle,
		OGType:       "website",
		Robots:       "index,follow",
	}
}

// ForHome generates SEO metadata for the homepage.
func (b *SEOBuilder) ForHome(description string) SEOMeta {
	meta := SEOMeta{
		Title:         b.siteName,
		Description:   description,
		CanonicalURL:  b.siteURL + "/",
		OGTitle:       b.siteName,
		OGDescription: description,
		OGType:        "website",
		Robots:        "index,follow",
	}

	meta.JSONLD = b.buildWebSiteJSONLD()
	return meta
}

// RenderHead returns escaped HTML tags for injection into a document <head>.
//
// The returned template.HTML is safe because dynamic attributes are escaped in
// this function. JSON-LD is expected to be generated by SEOBuilder or trusted
// plugin code before being assigned to SEOMeta.JSONLD.
func (b *SEOBuilder) RenderHead(meta SEOMeta) template.HTML {
	var sb strings.Builder

	if meta.Description != "" {
		sb.WriteString(fmt.Sprintf(`<meta name="description" content="%s">`+"\n", escAttr(meta.Description)))
	}
	if meta.Robots != "" {
		sb.WriteString(fmt.Sprintf(`<meta name="robots" content="%s">`+"\n", escAttr(meta.Robots)))
	}
	if meta.CanonicalURL != "" {
		sb.WriteString(fmt.Sprintf(`<link rel="canonical" href="%s">`+"\n", escAttr(meta.CanonicalURL)))
	}

	// Favicon — used by browsers and surfaced in Google search results.
	if meta.SiteIcon != "" {
		sb.WriteString(string(FaviconLinks(meta.SiteIcon)))
	}

	// Open Graph
	if meta.OGTitle != "" {
		sb.WriteString(fmt.Sprintf(`<meta property="og:title" content="%s">`+"\n", escAttr(meta.OGTitle)))
	}
	if meta.OGDescription != "" {
		sb.WriteString(fmt.Sprintf(`<meta property="og:description" content="%s">`+"\n", escAttr(meta.OGDescription)))
	}
	if meta.OGImage != "" {
		sb.WriteString(fmt.Sprintf(`<meta property="og:image" content="%s">`+"\n", escAttr(meta.OGImage)))
	}
	if meta.OGType != "" {
		sb.WriteString(fmt.Sprintf(`<meta property="og:type" content="%s">`+"\n", escAttr(meta.OGType)))
	}

	// JSON-LD
	if meta.JSONLD != "" {
		sb.WriteString(`<script type="application/ld+json">` + "\n")
		sb.WriteString(meta.JSONLD)
		sb.WriteString("\n</script>\n")
	}

	return template.HTML(sb.String())
}

// FaviconLinks renders the site icon declarations used by browsers and search
// engines. The generated /favicon.ico is declared first because crawlers often
// probe it directly with HEAD before considering image-specific declarations.
func FaviconLinks(siteIcon string) template.HTML {
	siteIcon = strings.TrimSpace(siteIcon)
	if siteIcon == "" {
		return ""
	}
	var sb strings.Builder
	sb.WriteString(`<link rel="icon" href="/favicon.ico" sizes="any">` + "\n")
	if siteIcon != "/favicon.ico" {
		icon := escAttr(siteIcon)
		typeAttr := ""
		iconPath := strings.Split(strings.Split(siteIcon, "?")[0], "#")[0]
		if mimeType := mime.TypeByExtension(path.Ext(iconPath)); mimeType != "" {
			typeAttr = fmt.Sprintf(` type="%s"`, escAttr(mimeType))
		}
		sb.WriteString(fmt.Sprintf(`<link rel="icon"%s sizes="192x192" href="%s">`+"\n", typeAttr, icon))
		sb.WriteString(fmt.Sprintf(`<link rel="apple-touch-icon" sizes="180x180" href="%s">`+"\n", icon))
	}
	return template.HTML(sb.String())
}

func (b *SEOBuilder) buildArticleJSONLD(c *content.Content, url string) string {
	ld := map[string]interface{}{
		"@context":     "https://schema.org",
		"@type":        "Article",
		"headline":     c.Title,
		"url":          url,
		"dateCreated":  c.CreatedAt.Format("2006-01-02T15:04:05Z"),
		"dateModified": c.UpdatedAt.Format("2006-01-02T15:04:05Z"),
	}
	if c.PublishedAt != nil {
		ld["datePublished"] = c.PublishedAt.Format("2006-01-02T15:04:05Z")
	}
	if c.Excerpt != "" {
		ld["description"] = truncate(c.Excerpt, 300)
	}
	if c.ImageURL != "" {
		ld["image"] = b.absoluteURL(c.ImageURL)
	}
	data, _ := json.MarshalIndent(ld, "", "  ")
	return string(data)
}

func (b *SEOBuilder) buildWebSiteJSONLD() string {
	ld := map[string]interface{}{
		"@context": "https://schema.org",
		"@type":    "WebSite",
		"name":     b.siteName,
		"url":      b.siteURL,
	}
	data, _ := json.MarshalIndent(ld, "", "  ")
	return string(data)
}

func (b *SEOBuilder) absoluteURL(path string) string {
	if strings.HasPrefix(path, "http") {
		return path
	}
	return b.siteURL + "/" + strings.TrimPrefix(path, "/")
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

func escAttr(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, `"`, "&quot;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
