// Code generated by gopress; DO NOT EDIT.
//
// Regenerate via `gopress gen`, `gopress serve`, or `gopress build`.
// Each blank import triggers the package's init() which calls
// core.RegisterTheme or core.RegisterPlugin.

package autoload

import (
	// Themes
	_ "github.com/0xmattg/go-press/themes/atelier-slate"
	_ "github.com/0xmattg/go-press/themes/axis-form"
	_ "github.com/0xmattg/go-press/themes/civic-estate"
	_ "github.com/0xmattg/go-press/themes/communa"
	_ "github.com/0xmattg/go-press/themes/financial-news"
	_ "github.com/0xmattg/go-press/themes/florafi"
	_ "github.com/0xmattg/go-press/themes/go-press-landing"
	_ "github.com/0xmattg/go-press/themes/modern-company"
	_ "github.com/0xmattg/go-press/themes/mono-journal"
	_ "github.com/0xmattg/go-press/themes/shop-starter"
	_ "github.com/0xmattg/go-press/themes/terra-trail"

	// Plugins
	_ "github.com/0xmattg/go-press/plugins/code-snippets"
	_ "github.com/0xmattg/go-press/plugins/commerce"
	_ "github.com/0xmattg/go-press/plugins/commerce-paypal"
	_ "github.com/0xmattg/go-press/plugins/commerce-usdt"
	_ "github.com/0xmattg/go-press/plugins/google-identity"
	_ "github.com/0xmattg/go-press/plugins/gopress-analytics"
	_ "github.com/0xmattg/go-press/plugins/gopress-mcp"
	_ "github.com/0xmattg/go-press/plugins/metamask-identity"
	_ "github.com/0xmattg/go-press/plugins/multilang"
	_ "github.com/0xmattg/go-press/plugins/seo-extras"
)
