// Code generated by gopress; DO NOT EDIT.
//
// Regenerate via `gopress gen`, `gopress serve`, or `gopress build`.
// Each blank import triggers the package's init() which calls
// core.RegisterTheme or core.RegisterPlugin.

package autoload

import (
	// Themes
	_ "go-press/themes/atelier-slate"
	_ "go-press/themes/axis-form"
	_ "go-press/themes/civic-estate"
	_ "go-press/themes/financial-news"
	_ "go-press/themes/florafi"
	_ "go-press/themes/go-press-landing"
	_ "go-press/themes/modern-company"
	_ "go-press/themes/terra-trail"

	// Plugins
	_ "go-press/plugins/code-snippets"
	_ "go-press/plugins/multilang"
	_ "go-press/plugins/seo-extras"
)
