package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	modulePath      = "go-press"
	autoloadRelPath = "internal/autoload/autoload_gen.go"
	autoloadPkg     = "autoload"
	themesRelDir    = "themes"
	pluginsRelDir   = "plugins"
	themeMarker     = "theme.toml"
	pluginMarker    = "plugin.toml"
)

// findRepoRoot walks up from cwd looking for go.mod with `module go-press`.
// It returns the absolute path to the module root.
func findRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := cwd
	for {
		gomod := filepath.Join(dir, "go.mod")
		if data, err := os.ReadFile(gomod); err == nil {
			// Confirm it's the go-press module to avoid running inside a
			// nested module that happens to have a go.mod.
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "module ") {
					if strings.TrimSpace(strings.TrimPrefix(line, "module")) == modulePath {
						return dir, nil
					}
					break
				}
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.mod for module %q starting from %s", modulePath, cwd)
		}
		dir = parent
	}
}

// scanModules returns sorted slugs of theme and plugin directories that are
// considered registerable. A directory qualifies when it contains both:
//   - a marker file at its root (theme.toml for themes, plugin.toml for plugins)
//   - at least one non-test .go file at its root
//
// Hidden directories and directories starting with "_" are skipped.
func scanModules(root string) (themes, plugins []string, err error) {
	themes, err = scanDir(filepath.Join(root, themesRelDir), themeMarker)
	if err != nil {
		return nil, nil, fmt.Errorf("scan themes: %w", err)
	}
	plugins, err = scanDir(filepath.Join(root, pluginsRelDir), pluginMarker)
	if err != nil {
		return nil, nil, fmt.Errorf("scan plugins: %w", err)
	}
	return themes, plugins, nil
}

func scanDir(dir, marker string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var slugs []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
			continue
		}
		sub := filepath.Join(dir, name)
		if !fileExists(filepath.Join(sub, marker)) {
			continue
		}
		if !hasGoFile(sub) {
			continue
		}
		slugs = append(slugs, name)
	}
	sort.Strings(slugs)
	return slugs, nil
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

// hasGoFile reports whether dir contains at least one non-test .go file
// at its root (no recursion). Test files are excluded so a directory that
// only contains _test.go isn't mistaken for a registerable package.
func hasGoFile(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") {
			continue
		}
		if strings.HasSuffix(name, "_test.go") {
			continue
		}
		return true
	}
	return false
}

// writeAutoload renders the autoload file from the discovered slugs and
// writes it to internal/autoload/autoload_gen.go. It returns true when the
// file content actually changed.
func writeAutoload(root string, themes, plugins []string) (bool, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gopress; DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Regenerate via `gopress gen`, `gopress serve`, or `gopress build`.\n")
	buf.WriteString("// Each blank import triggers the package's init() which calls\n")
	buf.WriteString("// core.RegisterTheme or core.RegisterPlugin.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", autoloadPkg)

	if len(themes) == 0 && len(plugins) == 0 {
		buf.WriteString("// No themes or plugins discovered.\n")
	} else {
		buf.WriteString("import (\n")
		if len(themes) > 0 {
			buf.WriteString("\t// Themes\n")
			for _, s := range themes {
				fmt.Fprintf(&buf, "\t_ %q\n", modulePath+"/"+themesRelDir+"/"+s)
			}
		}
		if len(plugins) > 0 {
			if len(themes) > 0 {
				buf.WriteString("\n")
			}
			buf.WriteString("\t// Plugins\n")
			for _, s := range plugins {
				fmt.Fprintf(&buf, "\t_ %q\n", modulePath+"/"+pluginsRelDir+"/"+s)
			}
		}
		buf.WriteString(")\n")
	}

	target := filepath.Join(root, autoloadRelPath)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return false, err
	}

	existing, _ := os.ReadFile(target)
	if bytes.Equal(existing, buf.Bytes()) {
		return false, nil
	}
	if err := os.WriteFile(target, buf.Bytes(), 0o644); err != nil {
		return false, err
	}
	return true, nil
}
