package main

import (
	"context"
	"errors"
	"flag"
	"log"
	"net/http"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"go-press/config"
	"go-press/core"
	"go-press/core/installer"
	"go-press/pkg/logger"
	pg "go-press/pkg/postgresql"

	// Theme imports — each theme's init() registers itself with core.RegisterTheme.
	_ "go-press/themes/atelier-slate"
	_ "go-press/themes/axis-form"
	_ "go-press/themes/civic-estate"
	_ "go-press/themes/financial-news"
	_ "go-press/themes/florafi"
	_ "go-press/themes/go-press-landing"
	_ "go-press/themes/modern-company"
	_ "go-press/themes/terra-trail"

	// Plugin imports — each plugin's init() registers itself with core.RegisterPlugin.
	_ "go-press/plugins/code-snippets"
	_ "go-press/plugins/multilang"
	_ "go-press/plugins/seo-extras"

	// Swagger docs — generated by swag init
	_ "go-press/docs"
)

// GoPress CMS Server
//
//	@title			GoPress API
//	@version		1.0
//	@description	GoPress CMS RESTful API — WordPress-like content management in Go
//	@termsOfService	https://hurricanetechs.com/terms
//
//	@contact.name	Hurricane Techs
//	@contact.email	sale@hurricanetechs.com
//
//	@host			localhost:8080
//	@BasePath		/api/v1
//
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				JWT Bearer token (format: Bearer {token})
//
//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						X-API-Key
//	@description				API key for authentication
func main() {
	configPathFlag := flag.String("config", "", "path to site config file (auto-detects from sites/ if omitted)")
	seedFlag := flag.Bool("seed", false, "force re-seed from seed.toml (drops existing content first)")
	flag.Parse()

	configPath, autoDiscovered := config.ResolveConfigPath(*configPathFlag)
	if autoDiscovered {
		log.Printf("Auto-discovered site config: %s", configPath)
	}

	cfg, cfgExists, err := config.LoadIfPresent(configPath)
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	serverAddr := config.ListenAddr(cfg)
	loggerMode := "debug"
	if cfg != nil && cfg.Server.Mode != "" {
		loggerMode = cfg.Server.Mode
	}
	logger.Setup(loggerMode)

	switcher := &core.HandlerSwitcher{}

	var (
		engineMu      sync.RWMutex
		currentEngine *core.Engine
	)

	activateApp := func(finalCfg *config.Config, finalConfigPath string) error {
		engine, err := core.BuildAndBootstrap(finalCfg, finalConfigPath, false)
		if err != nil {
			return err
		}

		switcher.Set(engine.Router)
		engine.OnRouterRebuild = switcher.Set

		engineMu.Lock()
		currentEngine = engine
		engineMu.Unlock()

		logger.Info("Installer completed; application mode enabled",
			"site", finalCfg.Site.Name,
			"theme", engine.ActiveThemeName(),
			"addr", serverAddr,
			"config", finalConfigPath,
		)
		return nil
	}

	installMode := !cfgExists || (cfg != nil && !cfg.Install.Completed)
	var installReason error

	if cfg != nil && !cfg.Install.Completed {
		if _, err := pg.NewConnection(cfg.PG); err != nil {
			installReason = err
		}
	}

	if installMode {
		inst := installer.New(configPath, cfg, installReason, activateApp)
		switcher.Set(inst.Router())
		logger.Info("GoPress installer mode", "addr", serverAddr, "config", configPath)
	} else {
		if cfg == nil {
			log.Fatal("No site config available")
		}

		engine, err := core.BuildAndBootstrap(cfg, configPath, !cfg.Install.Completed)
		if err != nil {
			log.Fatalf("Failed to bootstrap application: %v", err)
		}

		// CLI -seed flag: import demo data for the active theme
		if *seedFlag {
			activeSlug := engine.ActiveThemeName()
			if seedPath := engine.ThemeDemoSeedPath(activeSlug); seedPath != "" {
				logger.Info("Importing theme demo data via -seed flag", "theme", activeSlug)
				if err := engine.ImportThemeDemoData(activeSlug); err != nil {
					log.Fatalf("Failed to import theme demo data: %v", err)
				}
			} else {
				logger.Warn("Active theme has no demo data", "theme", activeSlug)
			}
		}

		switcher.Set(engine.Router)
		engine.OnRouterRebuild = switcher.Set

		engineMu.Lock()
		currentEngine = engine
		engineMu.Unlock()

		logger.Info("GoPress running",
			"site", cfg.Site.Name,
			"theme", engine.ActiveThemeName(),
			"addr", serverAddr,
		)
	}

	server := &http.Server{
		Addr:         serverAddr,
		Handler:      switcher,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 15 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.Error("HTTP server stopped unexpectedly", "error", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	engineMu.RLock()
	engine := currentEngine
	engineMu.RUnlock()
	if engine != nil {
		if err := engine.Shutdown(ctx); err != nil {
			logger.Error("Engine shutdown error", "error", err)
		}
	}

	if err := server.Shutdown(ctx); err != nil && !errors.Is(err, http.ErrServerClosed) {
		logger.Error("HTTP shutdown error", "error", err)
	}
}
